### PR TITLE
Make fitted carpets rotatable and mirrorable

### LINKED ISSUE #248: Regarding some errors with the carpets
When loading my building structures using data packs, carpets may have some incorrect generation, and I wonder if this issue can be 

Image

[latest.log](https://github.com/user-attachments/files/22188141/latest.log)

### PR DESCRIPTION
**Pull request by Elenterius**
This fixes #248 by making the fitted carpets blockstate properly rotatable and mirrorable.
Basically the bug boils down to not having the needed methods implemented that are usually called by structure gen and schematics (e.g. Create mod) when they place down blocks with suppressed block updates.

### CODE REVIEW

**Comment by KnightMiner** [comment]
That was my guess for the bug, hence asking them for more context to confirm it was a rotation issue and not something else (e.g. block update ordering being weird). I'll take a look at your implementation in more detail when I get a chance, hopefully later this week.

File: src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java [hunk 1]
```diff
@@ -100,4 +105,71 @@ private static int getBoundsKey(BlockState state) {
   public VoxelShape getShape(BlockState state, BlockGetter world, BlockPos pos, CollisionContext context) {
     return BOUNDS[getBoundsKey(state)];
   }
+
+  @Override
+  public BlockState rotate(BlockState state, Rotation rotation) {
+    BlockState newState = defaultBlockState();
+
+    if (state.getValue(NORTHWEST)) {
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java]: I can't help but wonder whether this might be easier to read if the rotation switch is the outside. Lets you do a quick exit for `NONE`, and for the rest could do something like the following for clockwise 90:

```java
newState.setValue(NORTHEAST, state.getValue(NORTHWEST))
        .setValue(NORTHWEST, state.getValue(SOUTHWEST));
        .setValue(SOUTHWEST, state.getValue(SOUTHEAST));
        .setValue(SOUTHEAST, state.getValue(NORTHEAST));

```

and the same for the others.

File: src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java [hunk 2]
```diff
@@ -100,4 +105,71 @@ private static int getBoundsKey(BlockState state) {
...
+
+  @Override
+  public BlockState mirror(BlockState state, Mirror mirror) {
+    return switch (mirror.rotation()) {
+      case INVERT_X -> {
+        BlockState newState = defaultBlockState();
+        newState = state.getValue(SOUTHWEST) ? newState.setValue(SOUTHEAST, true): newState;
+        newState = state.getValue(SOUTHEAST) ? newState.setValue(SOUTHWEST, true): newState;
+        newState = state.getValue(NORTHWEST) ? newState.setValue(NORTHEAST, true): newState;
+        newState = state.getValue(NORTHEAST) ? newState.setValue(NORTHWEST, true): newState;
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java]: Same thing here, can just do `newState.setValue(SOUTHWEST, state.getValue(SOUTHEAST))` to simplify the logic. Doesn't matter if we pass in false and its already false.

If you are going to prefer the if, I'd rather them be proper if statements instead of terinaries, e.g. `if (state.getValue(NORTHEAST)) newState = newState.setValue(NORTHWEST, true);`. Probably about as easy to read, removes a lot of redundancies.

File: src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java (hunk 1 above)
Comment (Elenterius) [reply src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java]: I applied your suggestion but i feel like it became less readable since you have to read it now from right to left to understand it.

File: src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java (hunk 2 above)
Comment (Elenterius) [reply src/main/java/knightminer/inspirations/tweaks/block/FittedCarpetBlock.java]: yeah your suggestion is pretty good for this case :) 
I don't even remember why i used ternary statements for this one.
