### PR TITLE
fixed crash on latest recommended Forge version (14.23.5.2768), fixes #89

### LINKED ISSUE #89: Crash with last forge
The game crash on start up with the new forge version.

Inpirations: 1.12.2-0.2.2
Mantle: 1.12-1.3.2.24
Forge: 14.23.5.2768

Crash report: https://pastebin.com/EsP4xBZw

### PR DESCRIPTION
**Pull request by SanAndreaP**
Given that I couldn't get the Access Transformer to transform the class PotionHelper$MixPredicate to be public (it is package-private now), I resorted to using reflection. Shouldn't impact performance, as they only get accessed during load and the field references are cached.

### CODE REVIEW

**Comment by SanAndreasP** [comment]
urgh, I love gradle sometimes... I've deleted the .gradle folder in my user profile folder and now it works. New PR incoming.

**Comment by SanAndreasP** [comment]
I can't get it to work for some reason with the AT. After re-indexing the project it shows me the same errors again. THe only field that gets transformed is the "reagent" field. I've attached an image to show how it works on my end. Maybe you have more luck with that, but I can't make a PR with errors in the project.
at_not_working

**Comment by KnightMiner** [comment]
Hmm, I'll look into it. I wonder if the Forge patch somehow breaks the AT. If I cannot figure it out I'll comment back here and we will see about reflection.

**Comment by KnightMiner** [comment]
I've looked into this more, and it seems the Forge patches are breaking the access transformer, so reflection is the only solution now. If you want to reopen this, feel free. Though, is there any reason you do not use ReflectionHelper like I did in utils? If there is a good reason, it might make sense to transition my other reflection to this method as well.

**Comment by SanAndreasP** [comment]
The only reason was I didn't know about it :V

I'll reopen, look into your ReflectionHelper and make appropriate changes to this PR when I get home.

**Comment by SanAndreasP** [comment]
I've updated this PR now. I still kept the ReflectionUtil, because there are 2 advantages to just using the ReflectionHelper:
1. fields are cached: better performance instead of always looking up the field when trying to access it.
2. easier update: all SRG names are in one class, so they can be easily changed once the mappings change.

If you want I can look through the code, replace the rest of the ReflectionHelper usage with the Util class and make a separate PR.

**Comment by KnightMiner** [comment]
Yeah, if you don't mind I'd prefer using the same reflection method everywhere. You can probably also remove the ATs, they are only needed if we directly access the fields.

It might be worth me switching to storing delegates rather than potion types as well, but that's an idea for another day.

**Comment by SanAndreasP** [comment]
updated PR again, with replacement of the ReflectionHelper occurences to ReflectionUtil

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+import net.minecraftforge.registries.IRegistryDelegate;
+
+import java.lang.reflect.Field;
+import java.lang.reflect.InvocationTargetException;
+import java.lang.reflect.Method;
+import java.util.HashMap;
+import java.util.Map;
+
+@SuppressWarnings("unchecked")
+public final class ReflectionUtil
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: Minor, but brackets on same line

File: src/main/java/knightminer/inspirations/library/Util.java [hunk 2]
```diff
@@ -80,10 +80,7 @@ public static ItemStack getStackFromState(IBlockState state) {
 
 		// first try getSilkTouchDrop, which just has to be protected
 		try {
-			Object stack = ReflectionHelper.findMethod(Block.class, "getSilkTouchDrop", "func_180643_i", IBlockState.class).invoke(block, state);
-			if(stack instanceof ItemStack) {
-				return (ItemStack) stack;
-			}
+			return ReflectionUtil.invokeGetSilkTouchDrop(block, state);
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/Util.java]: Since this is abstracted out, it might be nice to not need the try/catch here, though I guess its a bit harder to tell "no result" from "failed to call method" then...

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+{
+	private ReflectionUtil() {}
+
+	private static final Map<Integer, Field> FIELDS = new HashMap<>();
+	private static final Map<Integer, Method> METHODS = new HashMap<>();
+
+	public static PotionType getMixPredicateInput(Object mixPredicate) {
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: Javadoc

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+	public static ItemStack invokeGetSilkTouchDrop(Block block, IBlockState state) {
+		ItemStack stack = invokeMethod(block, "getSilkTouchDrop", "func_180643_i", 0, true, new Class[] {IBlockState.class}, state);
+		if(stack != null) {
+			return stack;
+		} else {
+			return ItemStack.EMPTY;
+		}
+	}
+
+	private static <T> T invokeMethod(Object instance, String mcpName, String srgName, int index, boolean throwException, Class[] paramTypes, Object... params) {
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: Not sure how I feel about the arbitrary index, is there any way to cache it using something like the srgName? Those are supposed to be unique. Same with below on fields

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+		Field f = FIELDS.get(index);
+		if(f == null) {
+			f = ReflectionHelper.findField(instance.getClass(), srgName, mcpName);
+			FIELDS.put(index, f);
+		}
+
+		try {
+			return (T) f.get(instance);
+		} catch(IllegalAccessException e) {
+			if(throwException) {
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: I'd rather have this not throw exceptions in general if it fails, but instead have some sort of error state (returning null is probably fine if you mark the methods nullable). Just log the exception here instead.

Same case on the method one, but not sure of how to deal with the fallback for getSilkTouchDrop

**Review by KnightMiner — CHANGES_REQUESTED** [review]
Looks mostly good, just had a few minor comments before pulling

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+		ItemStack stack = invokeMethod(block, "getSilkTouchDrop", "func_180643_i", 0, true, new Class[] {IBlockState.class}, state);
+		if(stack != null) {
+			return stack;
+		} else {
+			return ItemStack.EMPTY;
+		}
+	}
+
+	private static <T> T invokeMethod(Object instance, String mcpName, String srgName, int index, boolean throwException, Class[] paramTypes, Object... params) {
+		Method m = METHODS.get(index);
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: Could use the map computeIfAbsent method here, looks a little cleaner

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+		} catch(IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
+			if(throwException) {
+				throw new RuntimeException(e);
+			} else {
+				return null;
+			}
+		}
+	}
+
+	private static <T> T getFieldValue(Object instance, String mcpName, String srgName, int index, boolean throwException) {
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: Could use a javadoc due to the extra set of methods

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+	 * @param instance The instance to be accessed. Cannot be <tt>null</tt>!
+	 * @param mcpName The name used in a development environment
+	 * @param srgName The name used in an obfuscated environment
+	 * @param <T> The type of the return value. Must be the same as or a superclass of the return type of the method! {@link Object}, if the method is <tt>void</tt>
+	 *
+	 * @return The return value of the method or null, if it fails or the method is <tt>void</tt>
+	 */
+	@Nullable
+	private static <T> T invokeMethod(@Nonnull final Object instance, final String mcpName, final String srgName, final Class[] paramTypes, final Object... params) {
+		Method m = METHODS.computeIfAbsent(srgName, key -> ReflectionHelper.findMethod(instance.getClass(), key, mcpName, paramTypes));
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: You have `key` and `mcpName` in the wrong order, causing it to use deobf names in dev and normal names in game. Its also giving me an exception here for failing to find `BlockColored::getSilkTouchDrop`, I assume the exact class matters for the reflection, so it should probably take a class argument as well (not sure if this affects the field one too, though I know that is difficult to do with the class being private, maybe let it pass in or be dynamic?)

One last thing: the exception is not being caught if thrown by reflection helper, this should be inside the try/catch with the method invocation (for the missing field/method call). Same in the field version.

**Review by KnightMiner — CHANGES_REQUESTED** [review]
Just one more thing then this should be good to pull

**Comment by SanAndreasP** [comment]
method names are now in the right order and proper exceptions are now catched.

The silk touch method is now properly looked up via the Block class.
I also added a way to lookup private classes and incorporated into the reflection stuff.

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 9]
```diff
@@ -0,0 +1,131 @@
...
+	/**
+	 * Looks up a class by its name, caches it for further use and returns it.<br>
+	 * If it can't find the class, it will be logged and <tt>null</tt> is returned.
+	 *
+	 * @param className The class name to be searched for
+	 * @return The class found or <tt>null</tt>, if the class is unavailable
+	 */
+	public static Class getClass(String className) {
+		try {
+			return CLASS.computeIfAbsent(className, key -> ReflectionHelper.getClass(Inspirations.class.getClassLoader(), key));
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: Does this need to be the main class, or can it use something like the registry. Reason I ask is because for the most part I keep classes in library from referencing anything outside of library.

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java [hunk 10]
```diff
@@ -0,0 +1,131 @@
...
+			return ((IRegistryDelegate<PotionType>) val).get();
+		} else { // fallback for older Forge versions
+			return (PotionType) val;
+		}
+	}
+
+	@Nullable
+	public static ItemStack invokeGetSilkTouchDrop(@Nonnull Block block, IBlockState state) {
+		ItemStack stack = invokeMethod(Block.class, block, "getSilkTouchDrop", "func_180643_i", new Class[] {IBlockState.class}, state);
+		if(stack != null) {
```
Comment (KnightMiner) [inline src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: Shouldn't this just return invokeMethod as we are using null as an error condition above?

Comment (SanAndreasP) [reply src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: right, forgot about that

File: src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java (hunk 9 above)
Comment (SanAndreasP) [reply src/main/java/knightminer/inspirations/library/util/ReflectionUtil.java]: I usually use the main class, but sure, I can use the registry

**Review by KnightMiner — APPROVED** [review]

**Comment by KnightMiner** [comment]
Alright, merged. Thanks!
